"""añadir genre a artist

Revision ID: 9be2f8ea632f
Revises: abdda0d75304
Create Date: 2021-05-19 17:36:56.510652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be2f8ea632f'
down_revision = 'abdda0d75304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genre')
    # ### end Alembic commands ###
